import type { BrandProfile } from "./types";
import { EXTRACTOR_VERSION } from "@/lib/extract/extractor-version";

/**
 * Synthetic BrandProfile for local UI preview (DEV_AUTH_BYPASS).
 * Mirrors `buildBrandProfile` field shapes; ≥3 entries per array where applicable.
 */
export function buildDemoBrandProfile(owner: string, name: string): BrandProfile {
  const slug = `${owner}/${name}`;
  const url = `https://github.com/${slug}`;
  const iso = new Date().toISOString();

  return {
    repo: {
      owner,
      name,
      branch: "main",
      url,
    },
    scannedAt: iso,
    scannedFromSha: "dev-preview",
    meta: {
      filesScanned: 42,
      cssSource: "app/globals.css (dev preview)",
      tailwindConfigPath: "tailwind.config.ts",
      shadcnConfigPath: "components.json",
      tailwindVersion: "4",
      projectName: name,
      extractorVersion: EXTRACTOR_VERSION,
      lastScanDurationMs: 1200,
    },
    colors: [
      {
        name: "primary",
        cssVariable: "--primary",
        value: "#8f23fa",
        hsl: "271 91% 38%",
        rgb: "rgb(143 35 250)",
        oklch: "oklch(0.55 0.25 290)",
        group: "brand",
        source: "app/globals.css:12",
        contrastOnWhite: 4.8,
        contrastOnBlack: 4.2,
        wcagAANormal: true,
        wcagAALarge: true,
        wcagAAA: false,
      },
      {
        name: "background",
        cssVariable: "--background",
        value: "#ffffff",
        hsl: "0 0% 100%",
        rgb: "rgb(255 255 255)",
        group: "surface",
        source: "app/globals.css:20",
        contrastOnWhite: 1,
        contrastOnBlack: 21,
        wcagAANormal: true,
        wcagAALarge: true,
        wcagAAA: true,
      },
      {
        name: "destructive",
        cssVariable: "--destructive",
        value: "#ef4444",
        hsl: "0 84% 60%",
        rgb: "rgb(239 68 68)",
        group: "semantic",
        source: "app/globals.css:28",
        contrastOnWhite: 3.8,
        contrastOnBlack: 5.2,
        wcagAANormal: true,
        wcagAALarge: true,
        wcagAAA: false,
      },
    ],
    typography: [
      {
        name: "text-h1",
        fontFamily: "var(--font-manrope), sans-serif",
        fontSize: "2rem",
        fontSizePx: 32,
        fontWeight: "700",
        fontWeightNumeric: 700,
        lineHeight: "1.2",
        letterSpacing: "-0.02em",
        source: "app/globals.css:80",
        category: "heading",
        tailwindClass: "text-h1",
      },
      {
        name: "base",
        fontFamily: "var(--font-sans), system-ui, sans-serif",
        fontSize: "1rem",
        fontSizePx: 16,
        fontWeight: "400",
        fontWeightNumeric: 400,
        lineHeight: "1.5",
        source: "tailwind-default",
        category: "body",
        tailwindClass: "text-base",
      },
      {
        name: "sm",
        fontFamily: "var(--font-sans), system-ui, sans-serif",
        fontSize: "0.875rem",
        fontSizePx: 14,
        fontWeight: "400",
        fontWeightNumeric: 400,
        lineHeight: "1.5",
        source: "tailwind-default",
        category: "utility",
        tailwindClass: "text-sm",
      },
    ],
    fonts: [
      {
        family: "Geist Sans",
        importMethod: "next/font/google",
        source: "app/layout.tsx:4",
        weights: [
          { value: "400", name: "Regular" },
          { value: "600", name: "Semibold" },
        ],
        styles: ["normal"],
        role: "primary",
        fallbacks: ["system-ui", "sans-serif"],
      },
      {
        family: "Geist Mono",
        importMethod: "next/font/google",
        source: "app/layout.tsx:8",
        weights: [{ value: "400", name: "Regular" }],
        styles: ["normal"],
        role: "code",
        fallbacks: ["ui-monospace", "monospace"],
      },
      {
        family: "Cal Sans",
        importMethod: "next/font/local",
        source: "app/fonts/cal-sans.ts",
        weights: [{ value: "600", name: "Semibold" }],
        styles: ["normal"],
        role: "display",
        fallbacks: ["var(--font-sans)", "sans-serif"],
      },
    ],
    spacing: [
      {
        name: "2",
        tailwindClasses: ["p-2", "m-2", "gap-2", "space-x-2", "space-y-2"],
        rem: "0.5rem",
        px: 8,
        source: "tailwind-default",
        isCustom: false,
      },
      {
        name: "4",
        tailwindClasses: ["p-4", "m-4", "gap-4", "space-x-4", "space-y-4"],
        rem: "1rem",
        px: 16,
        source: "tailwind-default",
        isCustom: false,
      },
      {
        name: "8",
        tailwindClasses: ["p-8", "m-8", "gap-8", "space-x-8", "space-y-8"],
        rem: "2rem",
        px: 32,
        source: "tailwind-default",
        isCustom: false,
      },
    ],
    shadows: [
      {
        name: "sm",
        tailwindClass: "shadow-sm",
        value: "0 1px 2px 0 rgba(0,0,0,0.05)",
        layers: [
          {
            offsetX: "0",
            offsetY: "1px",
            blur: "2px",
            spread: "0",
            color: "rgba(0,0,0,0.05)",
            colorHex: "#0000000d",
            inset: false,
          },
        ],
        source: "tailwind-default",
        isCustom: false,
      },
      {
        name: "md",
        tailwindClass: "shadow-md",
        value: "0 4px 12px rgba(0,0,0,0.08)",
        layers: [
          {
            offsetX: "0",
            offsetY: "4px",
            blur: "12px",
            spread: "0",
            color: "rgba(0,0,0,0.08)",
            colorHex: "#00000014",
            inset: false,
          },
        ],
        source: "tailwind (preview)",
        isCustom: false,
      },
    ],
    radii: [
      {
        name: "md",
        tailwindClass: "rounded-md",
        value: "0.375rem",
        px: 6,
        source: "tailwind-default",
        isCustom: false,
      },
      {
        name: "lg",
        tailwindClass: "rounded-lg",
        value: "0.5rem",
        px: 8,
        source: "tailwind-default",
        isCustom: false,
      },
      {
        name: "full",
        tailwindClass: "rounded-full",
        value: "9999px",
        px: 9999,
        source: "tailwind-default",
        isCustom: false,
      },
    ],
    borders: [
      {
        name: "border",
        width: "1px",
        style: "solid",
        color: "#e5e7eb",
        colorToken: "--border",
        source: "app/globals.css:40",
        borderGroup: "source",
      },
      {
        name: "w-2",
        width: "2px",
        style: "solid",
        color: "#e5e7eb",
        source: "tailwind-default",
        borderGroup: "width",
      },
      {
        name: "c-current",
        width: "1px",
        style: "solid",
        color: "#000000",
        source: "tailwind-default",
        borderGroup: "color",
      },
    ],
    animations: [
      {
        name: "pulse",
        type: "keyframes",
        tailwindClass: "animate-pulse",
        duration: "2s",
        timingFunction: "cubic-bezier(0.4, 0, 0.6, 1)",
        keyframes: "@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }",
        source: "tailwind (preview)",
        isCustom: false,
      },
      {
        name: "spin",
        type: "keyframes",
        tailwindClass: "animate-spin",
        duration: "1s",
        timingFunction: "linear",
        source: "tailwind (preview)",
        isCustom: false,
      },
    ],
    breakpoints: [
      { name: "sm", value: "640px", px: 640, source: "tailwind-default", isCustom: false },
      { name: "md", value: "768px", px: 768, source: "tailwind-default", isCustom: false },
      { name: "lg", value: "1024px", px: 1024, source: "tailwind-default", isCustom: false },
    ],
    opacity: [
      { name: "50", value: 0.5, percentage: "50%", source: "tailwind-default", isCustom: false },
      { name: "80", value: 0.8, percentage: "80%", source: "tailwind-default", isCustom: false },
      { name: "20", value: 0.2, percentage: "20%", source: "tailwind (preview)", isCustom: true },
    ],
    zIndex: [
      {
        name: "10",
        value: 10,
        tailwindClass: "z-10",
        source: "tailwind-default",
        isCustom: false,
        inferredRole: "Elevated UI",
      },
      {
        name: "100",
        value: 100,
        tailwindClass: "z-100",
        source: "tailwind (preview)",
        isCustom: true,
        inferredRole: "Fixed headers",
      },
      {
        name: "50",
        value: 50,
        tailwindClass: "z-50",
        source: "tailwind (preview)",
        isCustom: false,
        inferredRole: "Modal overlays",
      },
    ],
    gradients: [
      {
        name: "hero",
        type: "linear",
        cssValue: "linear-gradient(135deg, #8f23fa 0%, #5b21b6 100%)",
        stops: [
          { color: "#8f23fa", colorHex: "#8f23fa", position: "0%" },
          { color: "#5b21b6", colorHex: "#5b21b6", position: "100%" },
        ],
        direction: "135deg",
        source: "app/globals.css:90",
      },
    ],
    assets: [
      {
        name: "logo",
        path: "public/logo.svg",
        type: "svg",
        category: "logo",
        dimensions: { width: 120, height: 40 },
        fileSize: 2048,
        fileSizeFormatted: "2 KB",
      },
      {
        name: "icon-32",
        path: "public/favicon-32x32.png",
        type: "png",
        category: "favicon",
        dimensions: { width: 32, height: 32 },
        fileSize: 512,
        fileSizeFormatted: "512 B",
      },
    ],
  };
}
